### ISSUE TITLE
Dates before 1970

### ISSUE THREAD

**Issue by ConnorSMaynes** [AndrewRPorter/yahoo-historical#11]
I am looking at historic data for S&P 500 and Yahoo has it starting from 1950. time.mktime cannot handle dates before 1970-01-01. This is a rare case, but I think a very important one. The solution is to use calendar.timegm, which can handle everything, in your fetch.py file in __init__ function.

Here is my proposed solution. It works for me using your original date format of (YYYY,MM,DD).

```
import calendar as cal

class Fetcher:
    def __init__(self, ticker, start, end=None, interval="1d"):
        self.start = int(cal.timegm(dt.datetime(*start).timetuple()))
        if end is not None:
            self.end = int(cal.timegm(dt.datetime(*start).timetuple()))
        else:
            self.end = int(time.time())
```

**Comment by AndrewRPorter** [comment]
Even with the suggested changes I was only able to get data to around 1980 for `AAPL`. What ticker are you using? I can look further into this.

**Comment by ConnorSMaynes** [comment]
^GSPC
It is for the S&P 500. AAPL stock didn't exist - I believe - before 1980. The S&P 500 is one of a few securities that has survived for more than the last 50 years.

**Comment by AndrewRPorter** [comment]
I am unable to produce your error with ticker `^GSPC`. I was able to get data from 1950 to 2019

```
>>> from yahoo_historical import Fetcher
>>> f = Fetcher("^GSPC", [1950,1,1])               
>>> f.getHistorical()
             Date         Open     ...        Adj Close      Volume
0      1950-01-03    16.660000     ...        16.660000     1260000
1      1950-01-04    16.850000     ...        16.850000     1890000
2      1950-01-05    16.930000     ...        16.930000     2550000
3      1950-01-06    16.980000     ...        16.980000     2010000
4      1950-01-09    17.080000     ...        17.080000     2520000
5      1950-01-10    17.030001     ...        17.030001     2160000
6      1950-01-11    17.090000     ...        17.090000     2630000
7      1950-01-12    16.760000     ...        16.760000     2970000
8      1950-01-13    16.670000     ...        16.670000     3330000
9      1950-01-16    16.719999     ...        16.719999     1460000
10     1950-01-17    16.860001     ...        16.860001     1790000
11     1950-01-18    16.850000     ...        16.850000     1570000
12     1950-01-19    16.870001     ...        16.870001     1170000
13     1950-01-20    16.900000     ...        16.900000     1440000
14     1950-01-23    16.920000     ...        16.920000     1340000
15     1950-01-24    16.860001     ...        16.860001     1250000
16     1950-01-25    16.740000     ...        16.740000     1700000
17     1950-01-26    16.730000     ...        16.730000     1150000
18     1950-01-27    16.820000     ...        16.820000     1250000
19     1950-01-30    17.020000     ...        17.020000     1640000
20     1950-01-31    17.049999     ...        17.049999     1690000
21     1950-02-01    17.049999     ...        17.049999     1810000
22     1950-02-02    17.230000     ...        17.230000     2040000
23     1950-02-03    17.290001     ...        17.290001     2210000
24     1950-02-06    17.320000     ...        17.320000     1490000
25     1950-02-07    17.230000     ...        17.230000     1360000
26     1950-02-08    17.209999     ...        17.209999     1470000
27     1950-02-09    17.280001     ...        17.280001     1810000
28     1950-02-10    17.240000     ...        17.240000     1790000
29     1950-02-14    17.059999     ...        17.059999     2210000
...           ...          ...     ...              ...         ...
17339  2018-11-28  2691.449951     ...      2743.790039  3951670000
17340  2018-11-29  2736.969971     ...      2737.800049  3560770000
17341  2018-11-30  2737.760010     ...      2760.169922  4658580000
17342  2018-12-03  2790.500000     ...      2790.370117  4186060000
17343  2018-12-04  2782.429932     ...      2700.060059  4499840000
17344  2018-12-06  2663.510010     ...      2695.949951  5141470000
17345  2018-12-07  2691.260010     ...      2633.080078  4216690000
17346  2018-12-10  2630.860107     ...      2637.719971  4151030000
17347  2018-12-11  2664.439941     ...      2636.780029  3905870000
17348  2018-12-12  2658.229980     ...      2651.070068  3955890000
17349  2018-12-13  2658.699951     ...      2650.540039  3927720000
17350  2018-12-14  2629.679932     ...      2599.949951  4035020000
17351  2018-12-17  2590.750000     ...      2545.939941  4616350000
17352  2018-12-18  2559.899902     ...      2546.159912  4470880000
17353  2018-12-19  2547.050049     ...      2506.959961  5127940000
17354  2018-12-20  2496.770020     ...      2467.419922  5585780000
17355  2018-12-21  2465.379883     ...      2416.620117  7609010000
17356  2018-12-24  2400.560059     ...      2351.100098  2613930000
17357  2018-12-26  2363.120117     ...      2467.699951  4233990000
17358  2018-12-27  2442.500000     ...      2488.830078  4096610000
17359  2018-12-28  2498.770020     ...      2485.739990  3702620000
17360  2018-12-31  2498.939941     ...      2506.850098  3442870000
17361  2019-01-02  2476.959961     ...      2510.030029  3733160000
17362  2019-01-03  2491.919922     ...      2447.889893  3822860000
17363  2019-01-04  2474.330078     ...      2531.939941  4213410000
17364  2019-01-07  2535.610107     ...      2549.689941  4104710000
17365  2019-01-08  2568.110107     ...      2574.409912  4083030000
17366  2019-01-09  2580.000000     ...      2584.959961  4052480000
17367  2019-01-10  2573.510010     ...      2596.639893  3704500000
17368  2019-01-11  2588.110107     ...      2582.320068   455810984
```

**Comment by ConnorSMaynes** [comment]
Python 3.7
Anaconda distribution - latest

```
>>> from yahoo_historical import Fetcher
>>> f = Fetcher( '^GSPC', (1900,1,1), (3000,1,1) )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\conno\Anaconda3\lib\site-packages\yahoo_historical\fetch.py", line 18, in __init__
    self.start = int(time.mktime(dt.datetime(start[0],start[1],start[2]).timetuple()))
OverflowError: mktime argument out of range
```

**Comment by AndrewRPorter** [comment]
I believe this to be a problem with your installation rather than the code itself:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_historical import Fetcher
>>> f = Fetcher( '^GSPC', (1900,1,1), (3000,1,1) )
```

```
Python 3.7.2 (default, Dec 25 2018, 03:50:46) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_historical import Fetcher
>>> f = Fetcher( '^GSPC', (1900,1,1), (3000,1,1) )
```

This seems to be related although I am unable to reproduce: https://stackoverflow.com/questions/2518706/python-mktime-overflow-error

Would you mind creating a pull request with the above code?

**Comment by AndrewRPorter** [comment]
https://github.com/AndrewRPorter/yahoo-historical/pull/12 fixes this
