### ISSUE TITLE
local variable 'crumb' referenced before assignment

### ISSUE THREAD

**Issue by mingwugmail** [AndrewRPorter/yahoo-historical#17]
I'm using Fetcher to download daily data, for some symbols, I got this error:

local variable 'crumb' referenced before assignment

**Comment by mingwugmail** [comment]
stack trace:

Traceback (most recent call last):                                                                       
    f = Fetcher(symbol, start)                                                                       
  File "///anaconda3/lib/python3.6/site-packages/yahoo_historical/fetch.py", line 25, in __init__
    self.cookie, self.crumb = self.init()                             
  File "///anaconda3/lib/python3.6/site-packages/yahoo_historical/fetch.py", line 46, in init
    return cookie, crumb  # return a tuple of crumb and cookie 
UnboundLocalError: local variable 'crumb' referenced before assignment

**Comment by AndrewRPorter** [comment]
@mingwugmail what symbols do you get this for?

**Comment by mingwugmail** [comment]
Ah, I realized it's mostly for de-listed symbols, e.g. DNKN.

But I also got another error for symbols like BAC:

  File "//lib/python3.6/site-packages/yahoo_historical/fetch.py", line 25, in __init__
    self.cookie, self.crumb = self.init()
  File "//lib/python3.6/site-packages/yahoo_historical/fetch.py", line 38, in init
    cookie = r.cookies["B"]
  File "//lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "//lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='B', domain=None, path=None"

**Comment by AndrewRPorter** [comment]
Right now I do not really have time to fix these issues. Feel free to create a PR with a fix if you are motivated enough. I will keep this issue for the time being on the off chance that I have some time to address this

**Comment by mingwugmail** [comment]
BTW, 

https://github.com/ranaroussi/yfinance

seems work more reliable, and is actively maintained.

**Comment by AndrewRPorter** [comment]
This has been fixed.
