### ISSUE TITLE
Foreign Exchange tickers throw an error when downloading historical data

### ISSUE THREAD

**Issue by gbigliardi** [AndrewRPorter/yahoo-historical#6]
Hi Andrew,

example:
    #l_tickers = ["^DJI","^IXIC","STM.MI"]  these works
    l_tickers = ["EURGBP=X","EURUSD=X"]  # these not

**Comment by AndrewRPorter** [comment]
Can you give me an example error message @gbigliardi

**Comment by gbigliardi** [comment]
yes.

Traceback (most recent call last):
  File "fetch.py", line 65, in <module>
    data = Fetcher(el, [2017,9,1], [2017,9,18])
  File "fetch.py", line 17, in __init__
    self.cookie, self.crumb = self.init()
  File "fetch.py", line 32, in init
    cookie = r.cookies['B']
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='B', domain=None, path=None"
gbigliardi@hmozero1:~/hmcrawler/UTN$

**Comment by AndrewRPorter** [comment]
See #8
